/** @type {import('tailwindcss').Config} */
export default {
    content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
    "./resources/**/*.{vue,js,ts,jsx,tsx}",
    // The line above covers EVERYTHING in /src and its subfolders.
    // If your components are in a different root folder, add it specifically:
    "./resources/js/components/*.{vue,js,ts,jsx,tsx}",
  ],
    theme: {
        extend: {
            colors: {
                "tertiary-container": "#00e3fe",
                "inverse-surface": "#001207",
                "on-primary-container": "#005d22",
                "tertiary-dim": "#005863",
                "on-primary": "#cfffce",
                "error": "#b02500",
                "primary-dim": "#005d22",
                "surface-container-lowest": "#ffffff",
                "secondary": "#00693f",
                "outline-variant": "#89b898",
                "on-tertiary": "#d9f8ff",
                "on-tertiary-container": "#004d57",
                "error-dim": "#b92902",
                "surface-bright": "#dcffe5",
                "on-tertiary-fixed": "#003840",
                "on-background": "#06361f",
                "on-surface": "#06361f",
                "surface-dim": "#9ce4b6",
                "on-primary-fixed-variant": "#006827",
                "outline": "#548064",
                "secondary-dim": "#005c36",
                "surface-container-low": "#c7fdd8",
                "secondary-fixed-dim": "#69e6a1",
                "primary-fixed-dim": "#4bee74",
                "surface-variant": "#a8ecbf",
                "inverse-primary": "#5cfd80",
                "on-secondary-fixed": "#004528",
                "primary": "#006a28",
                "error-container": "#f95630",
                "primary-container": "#5cfd80",
                "surface-container": "#bbf6ce",
                "secondary-container": "#78f5ae",
                "on-secondary": "#cbffda",
                "surface": "#dcffe5",
                "inverse-on-surface": "#79a789",
                "surface-container-highest": "#a8ecbf",
                "on-secondary-container": "#005a35",
                "surface-tint": "#006a28",
                "tertiary-fixed-dim": "#00d4ed",
                "on-surface-variant": "#39644a",
                "secondary-fixed": "#78f5ae",
                "on-primary-fixed": "#004819",
                "on-error-container": "#520c00",
                "on-secondary-fixed-variant": "#00653c",
                "tertiary-fixed": "#00e3fe",
                "surface-container-high": "#b2f1c7",
                "primary-fixed": "#5cfd80",
                "on-tertiary-fixed-variant": "#005762",
                "tertiary": "#006572",
                "background": "#dcffe5",
                "on-error": "#ffefec",

            },
            fontFamily: {
                "headline": ["Manrope"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
        },
    },
    plugins: [],
}
