<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('provider_operations', function (Blueprint $table) {
            $table->id();

            $table->foreignId('transaction_id')
                ->constrained()
                ->restrictOnDelete();

            $table->string('provider');

            $table->string('operation');

            // Reference generated by your application.
            $table->string('client_reference')->unique();

            // Reference returned/generated by the provider.
            $table->string('provider_reference')->nullable();

            $table->string('status');

            $table->unsignedInteger('attempt_number')->default(1);

            $table->string('response_code')->nullable();

            $table->text('failure_reason')->nullable();

            $table->json('request_payload')->nullable();
            $table->json('response_payload')->nullable();

            $table->timestamp('requested_at')->nullable();
            $table->timestamp('last_attempt_at')->nullable();
            $table->timestamp('completed_at')->nullable();

            $table->timestamps();

            $table->index([
                'transaction_id',
                'status',
            ]);

            $table->index([
                'provider',
                'provider_reference',
            ]);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('provider_operations');
    }
};
