<?php

/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Api
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Twilio\Rest\Api;

use Twilio\Domain;
use Twilio\Exceptions\TwilioException;
use Twilio\InstanceContext;
use Twilio\ListResource;
use Twilio\Rest\Api\V2010\Account\AddressList;
use Twilio\Rest\Api\V2010\Account\ApplicationList;
use Twilio\Rest\Api\V2010\Account\AuthorizedConnectAppList;
use Twilio\Rest\Api\V2010\Account\AvailablePhoneNumberCountryList;
use Twilio\Rest\Api\V2010\Account\BalanceList;
use Twilio\Rest\Api\V2010\Account\CallList;
use Twilio\Rest\Api\V2010\Account\ConferenceList;
use Twilio\Rest\Api\V2010\Account\ConnectAppList;
use Twilio\Rest\Api\V2010\Account\IncomingPhoneNumberList;
use Twilio\Rest\Api\V2010\Account\KeyList;
use Twilio\Rest\Api\V2010\Account\MessageList;
use Twilio\Rest\Api\V2010\Account\NewKeyList;
use Twilio\Rest\Api\V2010\Account\NewSigningKeyList;
use Twilio\Rest\Api\V2010\Account\NotificationList;
use Twilio\Rest\Api\V2010\Account\OutgoingCallerIdList;
use Twilio\Rest\Api\V2010\Account\QueueList;
use Twilio\Rest\Api\V2010\Account\RecordingList;
use Twilio\Rest\Api\V2010\Account\ShortCodeList;
use Twilio\Rest\Api\V2010\Account\SigningKeyList;
use Twilio\Rest\Api\V2010\Account\SipList;
use Twilio\Rest\Api\V2010\Account\TokenList;
use Twilio\Rest\Api\V2010\Account\TranscriptionList;
use Twilio\Rest\Api\V2010\Account\UsageList;
use Twilio\Rest\Api\V2010\Account\ValidationRequestList;
use Twilio\Rest\Api\V2010\AccountContext;
use Twilio\Rest\Api\V2010\AccountInstance;
use Twilio\Rest\Api\V2010\AccountList;
use Twilio\Version;

/**
 * @property AccountList $accounts
 * @property AccountContext $account
 * @property RecordingList $recordings
 * @property UsageList $usage
 * @property MessageList $messages
 * @property KeyList $keys
 * @property NewKeyList $newKeys
 * @property ApplicationList $applications
 * @property IncomingPhoneNumberList $incomingPhoneNumbers
 * @property ConferenceList $conferences
 * @property CallList $calls
 * @property OutgoingCallerIdList $outgoingCallerIds
 * @property ValidationRequestList $validationRequests
 * @property TranscriptionList $transcriptions
 * @property ConnectAppList $connectApps
 * @property AuthorizedConnectAppList $authorizedConnectApps
 * @property TokenList $tokens
 * @property BalanceList $balance
 * @property SipList $sip
 * @property NotificationList $notifications
 * @property AvailablePhoneNumberCountryList $availablePhoneNumbers
 * @property AddressList $addresses
 * @property QueueList $queues
 * @property ShortCodeList $shortCodes
 * @property SigningKeyList $signingKeys
 * @property NewSigningKeyList $newSigningKeys
 *
 * @method \Twilio\Rest\Api\V2010\AccountContext accounts(string $sid)
 * @method \Twilio\Rest\Api\V2010\Account\AddressContext addresses(string $sid)
 * @method \Twilio\Rest\Api\V2010\Account\ApplicationContext applications(string $sid)
 * @method \Twilio\Rest\Api\V2010\Account\AuthorizedConnectAppContext authorizedConnectApps(string $connectAppSid)
 * @method \Twilio\Rest\Api\V2010\Account\AvailablePhoneNumberCountryContext availablePhoneNumbers(string $countryCode)
 * @method \Twilio\Rest\Api\V2010\Account\CallContext calls(string $sid)
 * @method \Twilio\Rest\Api\V2010\Account\ConferenceContext conferences(string $sid)
 * @method \Twilio\Rest\Api\V2010\Account\ConnectAppContext connectApps(string $sid)
 * @method \Twilio\Rest\Api\V2010\Account\IncomingPhoneNumberContext incomingPhoneNumbers(string $sid)
 * @method \Twilio\Rest\Api\V2010\Account\KeyContext keys(string $sid)
 * @method \Twilio\Rest\Api\V2010\Account\MessageContext messages(string $sid)
 * @method \Twilio\Rest\Api\V2010\Account\NotificationContext notifications(string $sid)
 * @method \Twilio\Rest\Api\V2010\Account\OutgoingCallerIdContext outgoingCallerIds(string $sid)
 * @method \Twilio\Rest\Api\V2010\Account\QueueContext queues(string $sid)
 * @method \Twilio\Rest\Api\V2010\Account\RecordingContext recordings(string $sid)
 * @method \Twilio\Rest\Api\V2010\Account\ShortCodeContext shortCodes(string $sid)
 * @method \Twilio\Rest\Api\V2010\Account\SigningKeyContext signingKeys(string $sid)
 * @method \Twilio\Rest\Api\V2010\Account\TranscriptionContext transcriptions(string $sid)
 */
class V2010 extends Version
{
    protected $_accounts;

    protected $_account = null;

    protected $_recordings = null;

    protected $_usage = null;

    protected $_messages = null;

    protected $_keys = null;

    protected $_newKeys = null;

    protected $_applications = null;

    protected $_incomingPhoneNumbers = null;

    protected $_conferences = null;

    protected $_calls = null;

    protected $_outgoingCallerIds = null;

    protected $_validationRequests = null;

    protected $_transcriptions = null;

    protected $_connectApps = null;

    protected $_authorizedConnectApps = null;

    protected $_tokens = null;

    protected $_balance = null;

    protected $_sip = null;

    protected $_notifications = null;

    protected $_availablePhoneNumbers = null;

    protected $_addresses = null;

    protected $_queues = null;

    protected $_shortCodes = null;

    protected $_signingKeys = null;

    protected $_newSigningKeys = null;

    /**
     * Construct the V2010 version of Api
     *
     * @param  Domain  $domain  Domain that contains the version
     */
    public function __construct(Domain $domain)
    {
        parent::__construct($domain);
        $this->version = '2010-04-01';
    }

    protected function getAccounts(): AccountList
    {
        if (! $this->_accounts) {
            $this->_accounts = new AccountList($this);
        }

        return $this->_accounts;
    }

    /**
     * @return AccountContext Account provided as the authenticating account
     */
    protected function getAccount(): AccountContext
    {
        if (! $this->_account) {
            $this->_account = new AccountContext(
                $this,
                $this->domain->getClient()->getAccountSid()
            );
        }

        return $this->_account;
    }

    /**
     * Setter to override the primary account
     *
     * @param  AccountContext|AccountInstance  $account  account to use as the primary
     *                                                   account
     */
    public function setAccount($account): void
    {
        $this->_account = $account;
    }

    protected function getRecordings(): RecordingList
    {
        return $this->account->recordings;
    }

    protected function getUsage(): UsageList
    {
        return $this->account->usage;
    }

    protected function getMessages(): MessageList
    {
        return $this->account->messages;
    }

    protected function getKeys(): KeyList
    {
        return $this->account->keys;
    }

    protected function getNewKeys(): NewKeyList
    {
        return $this->account->newKeys;
    }

    protected function getApplications(): ApplicationList
    {
        return $this->account->applications;
    }

    protected function getIncomingPhoneNumbers(): IncomingPhoneNumberList
    {
        return $this->account->incomingPhoneNumbers;
    }

    protected function getConferences(): ConferenceList
    {
        return $this->account->conferences;
    }

    protected function getCalls(): CallList
    {
        return $this->account->calls;
    }

    protected function getOutgoingCallerIds(): OutgoingCallerIdList
    {
        return $this->account->outgoingCallerIds;
    }

    protected function getValidationRequests(): ValidationRequestList
    {
        return $this->account->validationRequests;
    }

    protected function getTranscriptions(): TranscriptionList
    {
        return $this->account->transcriptions;
    }

    protected function getConnectApps(): ConnectAppList
    {
        return $this->account->connectApps;
    }

    protected function getAuthorizedConnectApps(): AuthorizedConnectAppList
    {
        return $this->account->authorizedConnectApps;
    }

    protected function getTokens(): TokenList
    {
        return $this->account->tokens;
    }

    protected function getBalance(): BalanceList
    {
        return $this->account->balance;
    }

    protected function getSip(): SipList
    {
        return $this->account->sip;
    }

    protected function getNotifications(): NotificationList
    {
        return $this->account->notifications;
    }

    protected function getAvailablePhoneNumbers(): AvailablePhoneNumberCountryList
    {
        return $this->account->availablePhoneNumbers;
    }

    protected function getAddresses(): AddressList
    {
        return $this->account->addresses;
    }

    protected function getQueues(): QueueList
    {
        return $this->account->queues;
    }

    protected function getShortCodes(): ShortCodeList
    {
        return $this->account->shortCodes;
    }

    protected function getSigningKeys(): SigningKeyList
    {
        return $this->account->signingKeys;
    }

    protected function getNewSigningKeys(): NewSigningKeyList
    {
        return $this->account->newSigningKeys;
    }

    /**
     * Magic getter to lazy load root resources
     *
     * @param  string  $name  Resource to return
     * @return ListResource The requested resource
     *
     * @throws TwilioException For unknown resource
     */
    public function __get(string $name)
    {
        $method = 'get'.\ucfirst($name);
        if (\method_exists($this, $method)) {
            return $this->$method();
        }

        throw new TwilioException('Unknown resource '.$name);
    }

    /**
     * Magic caller to get resource contexts
     *
     * @param  string  $name  Resource to return
     * @param  array  $arguments  Context parameters
     * @return InstanceContext The requested resource context
     *
     * @throws TwilioException For unknown resource
     */
    public function __call(string $name, array $arguments): InstanceContext
    {
        $property = $this->$name;
        if (\method_exists($property, 'getContext')) {
            return \call_user_func_array([$property, 'getContext'], $arguments);
        }

        throw new TwilioException('Resource does not have a context');
    }

    /**
     * Provide a friendly representation
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        return '[Twilio.Api.V2010]';
    }
}
