<?php

/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Assistants
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Twilio\Rest\Assistants\V1\Assistant;

use Twilio\Exceptions\TwilioException;
use Twilio\Http\Response;
use Twilio\ListResource;
use Twilio\Metadata\ResourceMetadata;
use Twilio\Values;
use Twilio\Version;

class MessageList extends ListResource
{
    /**
     * Construct the MessageList
     *
     * @param  Version  $version  Version that contains the resource
     * @param  string  $id  the Assistant ID.
     */
    public function __construct(
        Version $version,
        string $id
    ) {
        parent::__construct($version);

        // Path Solution
        $this->solution = [
            'id' => $id,

        ];
        $this->uri = '/Assistants/'.\rawurlencode($id)
        .'/Messages';
    }

    /**
     * Helper function for Create
     *


     * @return Response Created Response
     *
     * @throws TwilioException When an HTTP error occurs.
     */
    private function _create(AssistantsV1ServiceAssistantSendMessageRequest $assistantsV1ServiceAssistantSendMessageRequest): Response
    {

        $headers = Values::of(['Content-Type' => 'application/json', 'Accept' => 'application/json']);
        $data = $assistantsV1ServiceAssistantSendMessageRequest->toArray();

        return $this->version->handleRequest('POST', $this->uri, [], $data, $headers, 'create');
    }

    /**
     * Create the MessageInstance
     *


     * @return MessageInstance Created MessageInstance
     *
     * @throws TwilioException When an HTTP error occurs.
     */
    public function create(AssistantsV1ServiceAssistantSendMessageRequest $assistantsV1ServiceAssistantSendMessageRequest): MessageInstance
    {
        $response = $this->_create($assistantsV1ServiceAssistantSendMessageRequest);

        return new MessageInstance(
            $this->version,
            $response->getContent(),
            $this->solution['id']
        );

    }

    /**
     * Create the MessageInstance with Metadata
     *


     * @return ResourceMetadata The Created Resource with Metadata
     *
     * @throws TwilioException When an HTTP error occurs.
     */
    public function createWithMetadata(AssistantsV1ServiceAssistantSendMessageRequest $assistantsV1ServiceAssistantSendMessageRequest): ResourceMetadata
    {
        $response = $this->_create($assistantsV1ServiceAssistantSendMessageRequest);
        $resource = new MessageInstance(
            $this->version,
            $response->getContent(),
            $this->solution['id']
        );

        return new ResourceMetadata(
            $resource,
            $response->getStatusCode(),
            $response->getHeaders()
        );
    }

    /**
     * Provide a friendly representation
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        return '[Twilio.Assistants.V1.MessageList]';
    }
}
